# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

message_cpp <- function() {
    .Call(`_polyglot_packaging_message_cpp`)
}

add_cpp <- function(a, b) {
    .Call(`_polyglot_packaging_add_cpp`, a, b)
}

